# Generated by Django 5.2 on 2025-06-09 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.product_table')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.register')),
            ],
        ),
    ]
