# Generated by Django 5.2 on 2025-06-10 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quantity',
            new_name='quantitys',
        ),
    ]
