# Generated by Django 5.2 on 2025-06-10 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0006_rename_quantity_cart_quantitys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quantitys',
            new_name='quantityes',
        ),
    ]
