# Generated by Django 5.2 on 2025-06-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0008_alter_cart_quantityes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantityes',
            field=models.IntegerField(default=1),
        ),
    ]
