# Generated by Django 5.2 on 2025-06-14 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0009_alter_cart_quantityes'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('order_date', models.DateTimeField()),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.product_table')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.register')),
            ],
        ),
    ]
