# Generated by Django 5.2 on 2025-06-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0011_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='product_status',
            field=models.CharField(default='order placed', max_length=30),
        ),
    ]
